import staking
import network
import privacy
import treasury
import other
import time
import lightning
from matplotlib import pyplot as plt

# this routine just calls the other scripts to plot each individual chart
# the config.py file contains any settings
# charts are automatically saved under dcrcharts one level up, grouped by month and resolution
sleepTmr = 5
# treasury charts
treasury.monthlyBalance()
time.sleep(sleepTmr)
treasury.monthlyFlows()
time.sleep(sleepTmr)
treasury.monthlyBalanceUSD()
time.sleep(sleepTmr)
treasury.tStats()
time.sleep(sleepTmr)
# staking
print('1')
staking.dailyTicketPrice()
time.sleep(sleepTmr)
staking.dailyStakePart()
time.sleep(sleepTmr)
staking.dailyTicketPoolValue()
time.sleep(sleepTmr)
staking.monthlyMissedVotes()
time.sleep(sleepTmr)
staking.dailyTicketsVoted()
time.sleep(sleepTmr)
staking.dailyTicketsBought()
time.sleep(sleepTmr)
staking.monthlyTicketsBought()
time.sleep(sleepTmr)
staking.monthlyTicketsVoted()
time.sleep(sleepTmr)
print('2')
# network
network.dailyHashrate()
time.sleep(sleepTmr)
network.dailyTxTfrValAdjNtv()
time.sleep(sleepTmr)
network.monthlyTxTfrValAdjNtv()
time.sleep(sleepTmr)
network.dailyTxTfrValAdjUSD()
time.sleep(sleepTmr)
network.monthlyTxTfrValAdjUSD()
time.sleep(sleepTmr)
network.monthlydexVolUSD()
time.sleep(sleepTmr)
network.monthlydexVolDCR()
time.sleep(sleepTmr)
network.monthlyfeesDCR()
time.sleep(sleepTmr)
network.monthlyTxCount()
time.sleep(sleepTmr)
print('3')
network.dailytxCount()
time.sleep(sleepTmr)
network.dailyBlockSize()
time.sleep(sleepTmr)
network.monthlyBlockSize()
time.sleep(sleepTmr)
network.monthlyblockchainSize()
time.sleep(sleepTmr)
network.dailyBlockTime()
time.sleep(sleepTmr)
network.monthlyBlockTime()
time.sleep(sleepTmr)
network.monthlyNewSupplyDist()
time.sleep(sleepTmr)
network.monthlyNewSupplyDistUSD()
time.sleep(sleepTmr)
network.NewSupplyDistDonut()
time.sleep(sleepTmr)
network.dailyVoteVersion()
time.sleep(sleepTmr)
network.dailyVoteVersion()
time.sleep(sleepTmr)
print('4')
# privacy

privacy.dailyVolume()
time.sleep(sleepTmr)
privacy.monthlyVolumeDCR()
time.sleep(sleepTmr)
privacy.monthlyVolumeUSD()
time.sleep(sleepTmr)
privacy.dailyMixUnspentPC()
time.sleep(sleepTmr)
privacy.dailyMixUnspentDCR()
time.sleep(sleepTmr)
print('5')
# pie charts
#other.hashDist()
other.nodesDist()
time.sleep(sleepTmr)
other.vspDist()
time.sleep(sleepTmr)
other.missedDist()
time.sleep(sleepTmr)
other.dailyNodeDist()
time.sleep(sleepTmr)
other.dailyHashDist()
time.sleep(sleepTmr)

print('7')
# lightning charts
lightning.dailyChannels()
time.sleep(sleepTmr)
lightning.dailyNodes()
time.sleep(sleepTmr)
lightning.dailyCapacity()
time.sleep(sleepTmr)
print('8')
# version distribution
other.blockVersDist()
time.sleep(sleepTmr)
other.voteVersDist()